"""add wellness health metrics

Revision ID: 0d8a0fe30240
Revises: 607990ac6b0f
Create Date: 2026-08-18 10:57:28.144587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8a0fe30240'
down_revision: Union[str, Sequence[str], None] = '607990ac6b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wellness_daily', sa.Column('resting_hr', sa.Integer(), nullable=True))
    op.add_column('wellness_daily', sa.Column('hrv', sa.Float(), nullable=True))
    op.add_column('wellness_daily', sa.Column('sleep_seconds', sa.Integer(), nullable=True))
    op.add_column('wellness_daily', sa.Column('sleep_score', sa.Float(), nullable=True))
    op.add_column('wellness_daily', sa.Column('sleep_quality', sa.Integer(), nullable=True))
    op.add_column('wellness_daily', sa.Column('avg_sleeping_hr', sa.Float(), nullable=True))
    op.add_column('wellness_daily', sa.Column('spo2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wellness_daily', 'spo2')
    op.drop_column('wellness_daily', 'avg_sleeping_hr')
    op.drop_column('wellness_daily', 'sleep_quality')
    op.drop_column('wellness_daily', 'sleep_score')
    op.drop_column('wellness_daily', 'sleep_seconds')
    op.drop_column('wellness_daily', 'hrv')
    op.drop_column('wellness_daily', 'resting_hr')
    # ### end Alembic commands ###
