"""add session execution analyses

Revision ID: 105576f889db
Revises: 18f10d052723
Create Date: 2026-08-29 15:47:07.644800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105576f889db'
down_revision: Union[str, Sequence[str], None] = '18f10d052723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_execution_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('training_session_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('technical_status', sa.String(length=30), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('attention_points', sa.JSON(), nullable=False),
    sa.Column('debriefing', sa.Text(), nullable=False),
    sa.Column('derived_results', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', name='uq_session_execution_analyses_training_session_id')
    )
    op.create_index(op.f('ix_session_execution_analyses_activity_id'), 'session_execution_analyses', ['activity_id'], unique=False)
    op.create_index(op.f('ix_session_execution_analyses_athlete_profile_id'), 'session_execution_analyses', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_session_execution_analyses_goal_type'), 'session_execution_analyses', ['goal_type'], unique=False)
    op.create_index(op.f('ix_session_execution_analyses_training_session_id'), 'session_execution_analyses', ['training_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_execution_analyses_training_session_id'), table_name='session_execution_analyses')
    op.drop_index(op.f('ix_session_execution_analyses_goal_type'), table_name='session_execution_analyses')
    op.drop_index(op.f('ix_session_execution_analyses_athlete_profile_id'), table_name='session_execution_analyses')
    op.drop_index(op.f('ix_session_execution_analyses_activity_id'), table_name='session_execution_analyses')
    op.drop_table('session_execution_analyses')
    # ### end Alembic commands ###
