"""add push badge count

Revision ID: 171e47ec4475
Revises: 4f19ee44d33e
Create Date: 2026-08-31 21:16:06.097733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171e47ec4475'
down_revision: Union[str, Sequence[str], None] = '4f19ee44d33e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "push_subscriptions",
        sa.Column(
            "badge_count",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_subscriptions', 'badge_count')
    # ### end Alembic commands ###
