"""add activity details intervals and streams

Revision ID: 18f10d052723
Revises: 4c9d1ebaf498
Create Date: 2026-08-28 16:33:11.431496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f10d052723'
down_revision: Union[str, Sequence[str], None] = '4c9d1ebaf498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_details',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('provider_lap_count', sa.Integer(), nullable=True),
    sa.Column('interval_summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('activity_intervals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('provider_interval_id', sa.String(length=100), nullable=True),
    sa.Column('interval_type', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=False),
    sa.Column('end_index', sa.Integer(), nullable=False),
    sa.Column('start_time_seconds', sa.Integer(), nullable=False),
    sa.Column('end_time_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=True),
    sa.Column('elapsed_time_seconds', sa.Integer(), nullable=True),
    sa.Column('average_speed_mps', sa.Float(), nullable=True),
    sa.Column('average_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('average_cadence', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_details.activity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'position', name='uq_activity_intervals_position')
    )
    op.create_index(op.f('ix_activity_intervals_activity_id'), 'activity_intervals', ['activity_id'], unique=False)
    op.create_table('activity_streams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('stream_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_details.activity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'stream_type', name='uq_activity_streams_type')
    )
    op.create_index(op.f('ix_activity_streams_activity_id'), 'activity_streams', ['activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_streams_activity_id'), table_name='activity_streams')
    op.drop_table('activity_streams')
    op.drop_index(op.f('ix_activity_intervals_activity_id'), table_name='activity_intervals')
    op.drop_table('activity_intervals')
    op.drop_table('activity_details')
    # ### end Alembic commands ###
