"""add activities

Revision ID: 1d1ea36d50aa
Revises: 4e36d50fc106
Create Date: 2026-08-17 20:28:15.282192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1ea36d50aa'
down_revision: Union[str, Sequence[str], None] = '4e36d50fc106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_activity_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport_type', sa.String(length=100), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('start_at_local', sa.DateTime(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('elapsed_time_seconds', sa.Integer(), nullable=True),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
    sa.Column('average_speed_mps', sa.Float(), nullable=True),
    sa.Column('max_speed_mps', sa.Float(), nullable=True),
    sa.Column('average_heart_rate', sa.Float(), nullable=True),
    sa.Column('max_heart_rate', sa.Float(), nullable=True),
    sa.Column('lactate_threshold_heart_rate', sa.Integer(), nullable=True),
    sa.Column('athlete_max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('average_cadence', sa.Float(), nullable=True),
    sa.Column('average_stride_m', sa.Float(), nullable=True),
    sa.Column('average_stance_time_ms', sa.Float(), nullable=True),
    sa.Column('average_vertical_oscillation_mm', sa.Float(), nullable=True),
    sa.Column('average_power_w', sa.Float(), nullable=True),
    sa.Column('average_altitude_m', sa.Float(), nullable=True),
    sa.Column('min_altitude_m', sa.Float(), nullable=True),
    sa.Column('max_altitude_m', sa.Float(), nullable=True),
    sa.Column('average_temperature_c', sa.Float(), nullable=True),
    sa.Column('min_temperature_c', sa.Float(), nullable=True),
    sa.Column('max_temperature_c', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('fitness_ctl', sa.Float(), nullable=True),
    sa.Column('fatigue_atl', sa.Float(), nullable=True),
    sa.Column('hr_load', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_activity_id', name='uq_activities_provider_activity')
    )
    op.create_index(op.f('ix_activities_athlete_profile_id'), 'activities', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_activities_start_at'), 'activities', ['start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_start_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_athlete_profile_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
