"""add training reminder notification preference

Revision ID: 23d2eab8e4b6
Revises: 29435f62a0ae
Create Date: 2026-09-01 17:44:08.115774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d2eab8e4b6'
down_revision: Union[str, Sequence[str], None] = '29435f62a0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'push_subscriptions',
        sa.Column(
            'training_reminder_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_subscriptions', 'training_reminder_enabled')
    # ### end Alembic commands ###
