"""add push notification preferences

Revision ID: 29435f62a0ae
Revises: 171e47ec4475
Create Date: 2026-09-01 10:05:54.369815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29435f62a0ae'
down_revision: Union[str, Sequence[str], None] = '171e47ec4475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'push_subscriptions',
        sa.Column(
            'system_notifications_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.add_column(
        'push_subscriptions',
        sa.Column(
            'system_sync_errors_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.add_column(
        'push_subscriptions',
        sa.Column(
            'system_backup_errors_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_subscriptions', 'system_backup_errors_enabled')
    op.drop_column('push_subscriptions', 'system_sync_errors_enabled')
    op.drop_column('push_subscriptions', 'system_notifications_enabled')
    # ### end Alembic commands ###
