"""add week type to weekly training plans

Revision ID: 346c9792bd3b
Revises: 740c1e4d5b77
Create Date: 2026-08-27 14:42:11.168106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346c9792bd3b'
down_revision: Union[str, Sequence[str], None] = '740c1e4d5b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weekly_training_plans",
        sa.Column(
            "week_type",
            sa.String(length=50),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "weekly_training_plans",
        "week_type",
    )
    # ### end Alembic commands ###
