"""add integration last synced at

Revision ID: 37e833480260
Revises: 92e32e1de121
Create Date: 2026-08-19 21:30:51.807143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e833480260'
down_revision: Union[str, Sequence[str], None] = '92e32e1de121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_connections', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_connections', 'last_synced_at')
    # ### end Alembic commands ###
