"""add races

Revision ID: 3ccfdaf4d29a
Revises: 37e833480260
Create Date: 2026-08-21 21:18:52.354324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccfdaf4d29a'
down_revision: Union[str, Sequence[str], None] = '37e833480260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('race_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('target_time_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('actual_distance_km', sa.Float(), nullable=True),
    sa.Column('actual_elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('actual_time_minutes', sa.Integer(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_activity_id'), 'races', ['activity_id'], unique=False)
    op.create_index(op.f('ix_races_athlete_profile_id'), 'races', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_races_date'), 'races', ['date'], unique=False)
    op.create_index(op.f('ix_races_priority'), 'races', ['priority'], unique=False)
    op.create_index(op.f('ix_races_status'), 'races', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_races_status'), table_name='races')
    op.drop_index(op.f('ix_races_priority'), table_name='races')
    op.drop_index(op.f('ix_races_date'), table_name='races')
    op.drop_index(op.f('ix_races_athlete_profile_id'), table_name='races')
    op.drop_index(op.f('ix_races_activity_id'), table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###
