"""add training session prescription

Revision ID: 4c9d1ebaf498
Revises: d2fef151fb72
Create Date: 2026-08-28 14:27:01.571867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9d1ebaf498'
down_revision: Union[str, Sequence[str], None] = 'd2fef151fb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('prescription', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'prescription')
    # ### end Alembic commands ###
