"""add athlete equipment

Revision ID: 4e36d50fc106
Revises: 84382db13ffa
Create Date: 2026-08-16 14:08:34.065797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e36d50fc106'
down_revision: Union[str, Sequence[str], None] = '84382db13ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_bikes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_bikes_athlete_profile_id'), 'athlete_bikes', ['athlete_profile_id'], unique=False)
    op.create_table('athlete_shoes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('max_distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_shoes_athlete_profile_id'), 'athlete_shoes', ['athlete_profile_id'], unique=False)
    op.create_table('athlete_watches',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_watches_athlete_profile_id'), 'athlete_watches', ['athlete_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_watches_athlete_profile_id'), table_name='athlete_watches')
    op.drop_table('athlete_watches')
    op.drop_index(op.f('ix_athlete_shoes_athlete_profile_id'), table_name='athlete_shoes')
    op.drop_table('athlete_shoes')
    op.drop_index(op.f('ix_athlete_bikes_athlete_profile_id'), table_name='athlete_bikes')
    op.drop_table('athlete_bikes')
    # ### end Alembic commands ###
