"""add athlete constraints

Revision ID: 52bb3bc84d26
Revises: 3ccfdaf4d29a
Create Date: 2026-08-22 11:34:03.682521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bb3bc84d26'
down_revision: Union[str, Sequence[str], None] = '3ccfdaf4d29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_constraints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('constraint_type', sa.String(length=30), nullable=False),
    sa.Column('availability', sa.String(length=30), nullable=False),
    sa.Column('running_allowed', sa.Boolean(), nullable=False),
    sa.Column('cross_training_allowed', sa.Boolean(), nullable=False),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_constraints_athlete_profile_id'), 'athlete_constraints', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_athlete_constraints_availability'), 'athlete_constraints', ['availability'], unique=False)
    op.create_index(op.f('ix_athlete_constraints_constraint_type'), 'athlete_constraints', ['constraint_type'], unique=False)
    op.create_index(op.f('ix_athlete_constraints_end_date'), 'athlete_constraints', ['end_date'], unique=False)
    op.create_index(op.f('ix_athlete_constraints_start_date'), 'athlete_constraints', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_constraints_start_date'), table_name='athlete_constraints')
    op.drop_index(op.f('ix_athlete_constraints_end_date'), table_name='athlete_constraints')
    op.drop_index(op.f('ix_athlete_constraints_constraint_type'), table_name='athlete_constraints')
    op.drop_index(op.f('ix_athlete_constraints_availability'), table_name='athlete_constraints')
    op.drop_index(op.f('ix_athlete_constraints_athlete_profile_id'), table_name='athlete_constraints')
    op.drop_table('athlete_constraints')
    # ### end Alembic commands ###
