"""add wellness daily

Revision ID: 607990ac6b0f
Revises: 1d1ea36d50aa
Create Date: 2026-08-18 10:05:52.697180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607990ac6b0f'
down_revision: Union[str, Sequence[str], None] = '1d1ea36d50aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellness_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fitness_ctl', sa.Float(), nullable=True),
    sa.Column('fatigue_atl', sa.Float(), nullable=True),
    sa.Column('ramp_rate', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('provider_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_profile_id', 'provider', 'date', name='uq_wellness_daily_profile_provider_date')
    )
    op.create_index(op.f('ix_wellness_daily_athlete_profile_id'), 'wellness_daily', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_wellness_daily_date'), 'wellness_daily', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellness_daily_date'), table_name='wellness_daily')
    op.drop_index(op.f('ix_wellness_daily_athlete_profile_id'), table_name='wellness_daily')
    op.drop_table('wellness_daily')
    # ### end Alembic commands ###
