"""add weekly training plans

Revision ID: 740c1e4d5b77
Revises: ee6d8cc9145c
Create Date: 2026-08-27 11:49:24.932784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740c1e4d5b77'
down_revision: Union[str, Sequence[str], None] = 'ee6d8cc9145c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_training_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('phase_week_index', sa.Integer(), nullable=False),
    sa.Column('target_load', sa.Float(), nullable=True),
    sa.Column('load_min', sa.Float(), nullable=True),
    sa.Column('load_max', sa.Float(), nullable=True),
    sa.Column('reference_duration_minutes', sa.Float(), nullable=True),
    sa.Column('target_duration_minutes', sa.Float(), nullable=True),
    sa.Column('long_endurance_reference_minutes', sa.Float(), nullable=True),
    sa.Column('schedule_pressure', sa.String(length=50), nullable=False),
    sa.Column('athlete_schedule_constrained', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_profile_id', 'week_start', name='uq_weekly_training_plans_athlete_week_start')
    )
    op.create_index(op.f('ix_weekly_training_plans_athlete_profile_id'), 'weekly_training_plans', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_weekly_training_plans_week_start'), 'weekly_training_plans', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_training_plans_week_start'), table_name='weekly_training_plans')
    op.drop_index(op.f('ix_weekly_training_plans_athlete_profile_id'), table_name='weekly_training_plans')
    op.drop_table('weekly_training_plans')
    # ### end Alembic commands ###
