"""add activity feel

Revision ID: 8122f4f7e3c1
Revises: 9ee9cae4245d
Create Date: 2026-08-18 16:37:17.681285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8122f4f7e3c1'
down_revision: Union[str, Sequence[str], None] = '9ee9cae4245d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('feel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'feel')
    # ### end Alembic commands ###
