"""add training sessions

Revision ID: 81cea4b0abda
Revises: 8122f4f7e3c1
Create Date: 2026-08-18 16:46:31.546652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cea4b0abda'
down_revision: Union[str, Sequence[str], None] = '8122f4f7e3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('intensity', sa.String(length=100), nullable=False),
    sa.Column('heart_rate_zone', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_activity_id'), 'training_sessions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_athlete_profile_id'), 'training_sessions', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_date'), 'training_sessions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_sessions_date'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_athlete_profile_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_activity_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
