"""add athlete profile data

Revision ID: 84382db13ffa
Revises: 9580194c5ad0
Create Date: 2026-08-16 13:23:40.807351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84382db13ffa'
down_revision: Union[str, Sequence[str], None] = '9580194c5ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete_profiles', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('max_heart_rate', sa.Integer(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('resting_heart_rate', sa.Integer(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('vma', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('threshold_heart_rate_1', sa.Integer(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('threshold_heart_rate_2', sa.Integer(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('weekly_sessions', sa.Integer(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('weekly_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('weekly_distance_km', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('available_days', sa.JSON(),nullable=False,server_default='[]',),)
    op.add_column('athlete_profiles', sa.Column('fatigue_threshold', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('experience', sa.String(length=30), nullable=False, server_default='beginner',),)
    op.add_column('athlete_profiles', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.add_column('athlete_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('carbohydrates_per_hour', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('fluids_per_hour', sa.Float(), nullable=True))
    op.add_column('athlete_profiles', sa.Column('sodium_per_hour', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete_profiles', 'sodium_per_hour')
    op.drop_column('athlete_profiles', 'fluids_per_hour')
    op.drop_column('athlete_profiles', 'carbohydrates_per_hour')
    op.drop_column('athlete_profiles', 'longitude')
    op.drop_column('athlete_profiles', 'latitude')
    op.drop_column('athlete_profiles', 'location_name')
    op.drop_column('athlete_profiles', 'experience')
    op.drop_column('athlete_profiles', 'fatigue_threshold')
    op.drop_column('athlete_profiles', 'available_days')
    op.drop_column('athlete_profiles', 'weekly_distance_km')
    op.drop_column('athlete_profiles', 'weekly_duration_minutes')
    op.drop_column('athlete_profiles', 'weekly_sessions')
    op.drop_column('athlete_profiles', 'threshold_heart_rate_2')
    op.drop_column('athlete_profiles', 'threshold_heart_rate_1')
    op.drop_column('athlete_profiles', 'vma')
    op.drop_column('athlete_profiles', 'resting_heart_rate')
    op.drop_column('athlete_profiles', 'max_heart_rate')
    op.drop_column('athlete_profiles', 'weight_kg')
    op.drop_column('athlete_profiles', 'height_cm')
    # ### end Alembic commands ###
