"""add daily contexts

Revision ID: 92e32e1de121
Revises: a3e0e5652927
Create Date: 2026-08-18 21:24:29.815821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e32e1de121'
down_revision: Union[str, Sequence[str], None] = 'a3e0e5652927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fatigue_subjective', sa.Integer(), nullable=False),
    sa.Column('pain_level', sa.Integer(), nullable=False),
    sa.Column('illness_status', sa.String(length=30), nullable=False),
    sa.Column('treatment_impact', sa.String(length=30), nullable=False),
    sa.Column('motivation', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_profile_id', 'date', name='uq_daily_context_profile_date')
    )
    op.create_index(op.f('ix_daily_contexts_athlete_profile_id'), 'daily_contexts', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_daily_contexts_date'), 'daily_contexts', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_contexts_date'), table_name='daily_contexts')
    op.drop_index(op.f('ix_daily_contexts_athlete_profile_id'), table_name='daily_contexts')
    op.drop_table('daily_contexts')
    # ### end Alembic commands ###
