"""add integration connections

Revision ID: 9ee9cae4245d
Revises: 0d8a0fe30240
Create Date: 2026-08-18 13:36:44.951428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee9cae4245d'
down_revision: Union[str, Sequence[str], None] = '0d8a0fe30240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_profile_id', 'provider', name='uq_integration_connection_profile_provider')
    )
    op.create_index(op.f('ix_integration_connections_athlete_profile_id'), 'integration_connections', ['athlete_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_connections_athlete_profile_id'), table_name='integration_connections')
    op.drop_table('integration_connections')
    # ### end Alembic commands ###
