"""add physiological measurements

Revision ID: aae290fc5415
Revises: 52bb3bc84d26
Create Date: 2026-08-22 15:40:14.175888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae290fc5415'
down_revision: Union[str, Sequence[str], None] = '52bb3bc84d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physiological_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('protocol', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physiological_measurements_athlete_profile_id'), 'physiological_measurements', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_confidence'), 'physiological_measurements', ['confidence'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_measured_at'), 'physiological_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_metric'), 'physiological_measurements', ['metric'], unique=False)
    op.create_index(op.f('ix_physiological_measurements_source'), 'physiological_measurements', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_physiological_measurements_source'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_metric'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_measured_at'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_confidence'), table_name='physiological_measurements')
    op.drop_index(op.f('ix_physiological_measurements_athlete_profile_id'), table_name='physiological_measurements')
    op.drop_table('physiological_measurements')
    # ### end Alembic commands ###
