"""add athlete sport disciplines

Revision ID: d2fef151fb72
Revises: f53a22b6b635
Create Date: 2026-08-28 11:52:55.667969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fef151fb72'
down_revision: Union[str, Sequence[str], None] = 'f53a22b6b635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Ajoute les disciplines sportives au profil athlète."""

    op.add_column(
        "athlete_profiles",
        sa.Column(
            "sport_disciplines",
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
    )

    with op.batch_alter_table(
        "athlete_profiles"
    ) as batch_op:
        batch_op.alter_column(
            "sport_disciplines",
            server_default=None,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete_profiles', 'sport_disciplines')
    # ### end Alembic commands ###
