"""add intervals workout sync metadata

Revision ID: da950a25c05f
Revises: 2adb0141bfde
Create Date: 2026-09-05 20:33:24.730062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da950a25c05f'
down_revision: Union[str, Sequence[str], None] = '2adb0141bfde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('intervals_external_id', sa.String(), nullable=True))
    op.add_column('training_sessions', sa.Column('intervals_event_id', sa.String(), nullable=True))
    op.add_column('training_sessions', sa.Column('intervals_sync_status', sa.String(), nullable=True))
    op.add_column('training_sessions', sa.Column('intervals_last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('training_sessions', sa.Column('intervals_payload_hash', sa.String(), nullable=True))
    op.add_column('training_sessions', sa.Column('intervals_sync_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_sessions', 'intervals_sync_error')
    op.drop_column('training_sessions', 'intervals_payload_hash')
    op.drop_column('training_sessions', 'intervals_last_synced_at')
    op.drop_column('training_sessions', 'intervals_sync_status')
    op.drop_column('training_sessions', 'intervals_event_id')
    op.drop_column('training_sessions', 'intervals_external_id')
    # ### end Alembic commands ###
