"""add daily athlete checkins

Revision ID: ee6d8cc9145c
Revises: 72a1783bfc9f
Create Date: 2026-08-26 10:30:23.801664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6d8cc9145c'
down_revision: Union[str, Sequence[str], None] = '72a1783bfc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('energy_rating', sa.Integer(), nullable=False),
    sa.Column('pain_wellness_rating', sa.Integer(), nullable=False),
    sa.Column('illness', sa.Boolean(), nullable=False),
    sa.Column('unavailable', sa.Boolean(), nullable=False),
    sa.Column('pain_locations', sa.JSON(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_profile_id', 'date', name='uq_daily_checkins_athlete_date')
    )
    op.create_index(op.f('ix_daily_checkins_athlete_profile_id'), 'daily_checkins', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_daily_checkins_date'), 'daily_checkins', ['date'], unique=False)
    op.create_table('daily_adaptation_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('checkin_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('recommendation', sa.String(length=2000), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checkin_id'], ['daily_checkins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkin_id', name='uq_daily_adaptation_proposals_checkin')
    )
    op.create_index(op.f('ix_daily_adaptation_proposals_athlete_profile_id'), 'daily_adaptation_proposals', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_daily_adaptation_proposals_checkin_id'), 'daily_adaptation_proposals', ['checkin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_adaptation_proposals_checkin_id'), table_name='daily_adaptation_proposals')
    op.drop_index(op.f('ix_daily_adaptation_proposals_athlete_profile_id'), table_name='daily_adaptation_proposals')
    op.drop_table('daily_adaptation_proposals')
    op.drop_index(op.f('ix_daily_checkins_date'), table_name='daily_checkins')
    op.drop_index(op.f('ix_daily_checkins_athlete_profile_id'), table_name='daily_checkins')
    op.drop_table('daily_checkins')
    # ### end Alembic commands ###
