"""add physiological test proposals

Revision ID: f53a22b6b635
Revises: 346c9792bd3b
Create Date: 2026-08-28 10:13:28.535439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53a22b6b635'
down_revision: Union[str, Sequence[str], None] = '346c9792bd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physiological_test_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_session_id', sa.Uuid(), nullable=True),
    sa.Column('protocol', sa.String(length=100), nullable=False),
    sa.Column('target_metrics', sa.JSON(), nullable=False),
    sa.Column('proposed_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('recommendation', sa.String(length=2000), nullable=False),
    sa.Column('replacement_stimulus', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_session_id'], ['training_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physiological_test_proposals_athlete_profile_id'), 'physiological_test_proposals', ['athlete_profile_id'], unique=False)
    op.create_index(op.f('ix_physiological_test_proposals_decision'), 'physiological_test_proposals', ['decision'], unique=False)
    op.create_index(op.f('ix_physiological_test_proposals_proposed_date'), 'physiological_test_proposals', ['proposed_date'], unique=False)
    op.create_index(op.f('ix_physiological_test_proposals_protocol'), 'physiological_test_proposals', ['protocol'], unique=False)
    op.create_index(op.f('ix_physiological_test_proposals_target_session_id'), 'physiological_test_proposals', ['target_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_physiological_test_proposals_target_session_id'), table_name='physiological_test_proposals')
    op.drop_index(op.f('ix_physiological_test_proposals_protocol'), table_name='physiological_test_proposals')
    op.drop_index(op.f('ix_physiological_test_proposals_proposed_date'), table_name='physiological_test_proposals')
    op.drop_index(op.f('ix_physiological_test_proposals_decision'), table_name='physiological_test_proposals')
    op.drop_index(op.f('ix_physiological_test_proposals_athlete_profile_id'), table_name='physiological_test_proposals')
    op.drop_table('physiological_test_proposals')
    # ### end Alembic commands ###
