"""add heart rate zones to athlete profile

Revision ID: f7188bb7dc22
Revises: 105576f889db
Create Date: 2026-08-31 09:50:27.558693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7188bb7dc22'
down_revision: Union[str, Sequence[str], None] = '105576f889db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'athlete_profiles',
        sa.Column(
            'heart_rate_zones',
            sa.JSON(),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athlete_profiles', 'heart_rate_zones')
    # ### end Alembic commands ###
